apiVersion: batch/v1
kind: Job
metadata:
  name: run-me
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:23.10
        command: ["/bin/bash",  "-c"]
        args: ["echo ${TF_OUTPUT_my_app_bucket_name}"]
      restartPolicy: Never
  backoffLimit: 1
